type Todo {
  _id: String!
  text: String
  description: String
  completed: Boolean
  created: String
  updated: String
}

type todoResponse {
  ok: Boolean!
  todo: Todo
  errors: [Error!]
}

type Query {
  getTodos: [Todo!]!
  getTodo(_id: String!): Todo!
}

type Mutation {
  addTodo(description: String, text: String!): todoResponse!
  updateTodo(_id: String!, text: String, description: String, completed: Boolean): todoResponse!
  deleteTodo(_id: String!): todoResponse!
}
