type Todo {
  _id: String!
  text: String!
  descripiton: String
  created: String
  updated: String
}

type Error {
  message: String!
}

type dataResponse {
  ok: Boolean!
  todo: Todo!
  errors: [Error!]
}

type withoutDataResponse {
  ok: Boolean!
  errors: [Error!]
}

type Query {
  getTodos: [Todo!]!
  getTodo(_id: String!): Todo
}

type Mutation {
  addTodo(descripiton: String, text: String!): dataResponse!
  updateTodo(_id: String!, text: String!): dataResponse!
  deleteTodo(_id: String!): withoutDataResponse!
}
